version: '3.7'
services:
  health:
    image: docker.lappsgrid.org/lappsgrid/health
    ports:
      - 8083:8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    secrets:
      - health.ini

secrets:
  health.ini:
    external: true